packages:
  - apps/*
  - packages/*
catalog:
  # Auth
  "@better-auth/expo": ^1.4.0
  better-auth: ^1.4.0

  # Database
  drizzle-orm: ^0.44.2
  drizzle-kit: ^0.31.2

  # Deploy
  "@cloudflare/workers-types": ^4.20250805.0
  alchemy: ^0.77.5
  wrangler: ^4.30.0

  # Tailwind CSS
  "@tailwindcss/postcss": ~4.1.17
  postcss: "^8.5.6"
  tailwind-merge: ^3.3.1
  tailwindcss: ~4.1.17

  # tRPC api
  "@tanstack/react-form": ^1.12.3
  "@tanstack/react-query": ^5.85.5
  "@trpc/client": ^11.5.0
  "@trpc/server": ^11.5.0
  "@trpc/tanstack-react-query": ^11.5.0

  # TypeScript utilities
  "@types/node": ^24.10.1
  typescript: ~5.9.2
  zod: ^4.1.12

  # Utilities
  dotenv: ^17.2.2

  # Misc
  hono: ^4.8.2
  # "@types/node": ^22.13.11

catalogs:
  react19:
    "@types/react": ~19.1.0
    "@types/react-dom": ~19.1.0
    react: 19.1.0
    react-dom: 19.1.0

nodeLinker: hoisted
